# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19fc1b1ba03fa578b16e46cca060eada1d5aa4a6a4d639fc2d6ccdc1f09357e7f3a28a192ff602096241f10ba51abe5f872e59ddbe16232f2a704a502a2b1fca

test:
  secret_key_base: bcd527c079207b856449fc2becb5e89b38cbffd283fcc799691420e33d43e6bb6424163df75fda8c30eb5bb08d0884107fb3abda07901554c87f8927b2b343ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
